/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesArchievedRouteImport } from './routes/notes/archieved'
import { Route as NotesAllRouteImport } from './routes/notes/all'

const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesArchievedRoute = NotesArchievedRouteImport.update({
  id: '/archieved',
  path: '/archieved',
  getParentRoute: () => NotesRoute,
} as any)
const NotesAllRoute = NotesAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => NotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/all': typeof NotesAllRoute
  '/notes/archieved': typeof NotesArchievedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/all': typeof NotesAllRoute
  '/notes/archieved': typeof NotesArchievedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/all': typeof NotesAllRoute
  '/notes/archieved': typeof NotesArchievedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes' | '/notes/all' | '/notes/archieved'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes' | '/notes/all' | '/notes/archieved'
  id: '__root__' | '/' | '/notes' | '/notes/all' | '/notes/archieved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/archieved': {
      id: '/notes/archieved'
      path: '/archieved'
      fullPath: '/notes/archieved'
      preLoaderRoute: typeof NotesArchievedRouteImport
      parentRoute: typeof NotesRoute
    }
    '/notes/all': {
      id: '/notes/all'
      path: '/all'
      fullPath: '/notes/all'
      preLoaderRoute: typeof NotesAllRouteImport
      parentRoute: typeof NotesRoute
    }
  }
}

interface NotesRouteChildren {
  NotesAllRoute: typeof NotesAllRoute
  NotesArchievedRoute: typeof NotesArchievedRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesAllRoute: NotesAllRoute,
  NotesArchievedRoute: NotesArchievedRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
